version: '3.4'

services:
  keycloak:
    container_name: keycloak
    image: vvotuskam/first-job-auth:latest
    env_file:
      - .env
    ports:
      - '8762:8762'
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  client-app:
    container_name: client-app
    image: vvotuskam/first-job-client-app:latest
    env_file:
      - .env
    ports:
      - '8080:8080'
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    env_file:
#      - .env
#    ports:
#      - "5050:80"
#    restart: unless-stopped

volumes:
  postgres_data: