version: '3.4'

services:
  keycloak:
    container_name: keycloak
    image: vvotuskam/first-job-auth:latest
    env_file:
      - .env
    ports:
      - '8762:8762'

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data

  client-app:
    container_name: client-app
    image: vvotuskam/first-job-client-app:latest
    env_file:
      - .env
    ports:
      - '8080:8080'

  content-service:
    container_name: content-service
    image: vvotuskam/first-job-content-service:latest
    env_file:
      - .env
    ports:
      - '8082:8082'
    volumes:
      - /root/images:/images

  notification:
    container_name: notification
    image: vvotuskam/first-job-notification:latest
    env_file:
      - .env
    ports:
      - '8083:8083'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: unless-stopped

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '2181:2181'
    env_file:
      - .env

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    env_file:
      - .env


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    ports:
      - "8888:8888"
    restart: always
    environment:
      SERVER_PORT: 8888
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

volumes:
  postgres_data: